fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

main:
    resource: "@MainBundle/Controller/Front/"
    type:     annotation
    prefix:   /

#REST
rest :
    type : rest
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: {_format: json}

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
