android_sections:
    type: rest
    resource: MainBundle\Controller\AndroidApi\SectionController
    prefix: android/sections
    options:
        expose: true

android_countries:
    type: rest
    resource: MainBundle\Controller\AndroidApi\CountryController
    prefix: android/countries
    options:
        expose: true

android_regids:
    type: rest
    resource: MainBundle\Controller\AndroidApi\RegIdController
    prefix: android/regids
    options:
        expose: true
