android_section:
    type: rest
    resource: MainBundle\Controller\AndroidApi\SectionController
    prefix: android/sections
    options:
        expose: true

android_country:
    type: rest
    resource: MainBundle\Controller\AndroidApi\CountryController
    prefix: android/countries
    options:
        expose: true

android_regid:
    type: rest
    resource: MainBundle\Controller\AndroidApi\RegIdController
    prefix: android/regids
    options:
        expose: true
