countries:
    type: rest
    resource: MainBundle\Controller\Api\CountryController
    prefix: countries
    options:
        expose: true

notifications:
    type: rest
    resource: MainBundle\Controller\Api\NotificationController
    prefix: notifications
    options:
        expose: true

sections:
    type: rest
    resource: MainBundle\Controller\Api\SectionController
    prefix: sections
    options:
        expose: true

regids:
    type: rest
    resource: MainBundle\Controller\Api\RegIdController
    prefix: regids
    options:
        expose: true

guides:
    type: rest
    resource: MainBundle\Controller\Api\GuideController
    prefix: guides
    options:
        expose: true

categories:
    type: rest
    resource: MainBundle\Controller\Api\CategoryController
    prefix: categories
    options:
        expose: true