services:
    main.notification.creator:
        class: MainBundle\Creator\NotificationCreator

    main.guide.creator:
            class: MainBundle\Creator\GuideCreator

    main.country.creator:
        class: MainBundle\Creator\CountryCreator

    main.section.creator:
        class: MainBundle\Creator\SectionCreator

    main.user.creator:
        class: MainBundle\Creator\UserCreator

    main.regid.creator:
        class: MainBundle\Creator\RegIdCreator


