services:
    main.notification.creator:
        class: MainBundle\Creator\NotificationCreator

    main.country.creator:
            class: MainBundle\Creator\CountryCreator

    main.section.creator:
            class: MainBundle\Creator\SectionCreator
