services:
    main.country.fetcher:
        class: MainBundle\Fetcher\CountryFetcher
        arguments:
            - "@doctrine.orm.entity_manager"


    main.notification.fetcher:
            class: MainBundle\Fetcher\NotificationFetcher
            arguments:
                - "@doctrine.orm.entity_manager"

    main.regid.fetcher:
        class: MainBundle\Fetcher\RegIdFetcher
        arguments:
            - "@doctrine.orm.entity_manager"

    main.section.fetcher:
            class: MainBundle\Fetcher\SectionFetcher
            arguments:
                - "@doctrine.orm.entity_manager"

    main.guide.fetcher:
                class: MainBundle\Fetcher\GuideFetcher
                arguments:
                    - "@doctrine.orm.entity_manager"
