services:
    main.notification.fetcher:
        class: MainBundle\Fetcher\NotificationFetcher
        arguments:
            - "@doctrine.orm.entity_manager"

    main.country.fetcher:
        class: MainBundle\Fetcher\CountryFetcher
        arguments:
            - "@doctrine.orm.entity_manager"

    main.section.fetcher:
            class: MainBundle\Fetcher\SectionFetcher
            arguments:
                - "@doctrine.orm.entity_manager"
