services:
    main.user.manager:
        class: MainBundle\Manager\UserManager
        arguments:
            - "@doctrine.orm.entity_manager"

    main.notification.manager:
        class: MainBundle\Manager\NotificationManager
        arguments:
            - "@doctrine.orm.entity_manager"

    main.country.manager:
        class: MainBundle\Manager\CountryManager
        arguments:
            - "@doctrine.orm.entity_manager"

    main.section.manager:
        class: MainBundle\Manager\SectionManager
        arguments:
            - "@doctrine.orm.entity_manager"

    main.regid.manager:
        class: MainBundle\Manager\RegIdManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@main.regid.creator"
