services:
    main.user.manager:
        class: MainBundle\Manager\UserManager
        arguments:
            - "@doctrine.orm.entity_manager"

    main.notification.manager:
            class: MainBundle\Manager\NotificationManager
            arguments:
                - "@doctrine.orm.entity_manager"

    main.country.manager:
            class: MainBundle\Manager\CountryCoManager
            arguments:
                - "@doctrine.orm.entity_manager"

