services:
    main.notification.service:
        class: MainBundle\Service\NotificationService
        arguments:
            - "@main.notification.manager"
            - "@main.section.fetcher"
            - "@main.notification.creator"
            - "@main.notification.helper"
            - "@main.regid.adapter"
            - "@security.authorization_checker"

    main.country.service:
            class: MainBundle\Service\CountryService
            arguments:
                - "@main.country.fetcher"

    main.section.service:
                class: MainBundle\Service\SectionService
                arguments:
                    - "@main.section.fetcher"

    main.import_countries.service:
        class: MainBundle\Service\ImportCountriesService
        arguments:
            - "@main.import_countries.reader"
            - "@main.country.manager"

    main.import_sections.service:
        class: MainBundle\Service\ImportSectionsService
        arguments:
            - "@main.import_sections.reader"
            - "@main.country.manager"
            - "@main.country.fetcher"
            - "@main.section.manager"
