country:
    type: rest
    resource: MainBundle\Controller\Api\CountryController
    prefix: countries
    options:
        expose: true

notification:
    type: rest
    resource: MainBundle\Controller\Api\NotificationController
    prefix: notifications
    options:
        expose: true

section:
    type: rest
    resource: MainBundle\Controller\Api\SectionController
    prefix: sections
    options:
        expose: true

android_section:
    type: rest
    resource: MainBundle\Controller\AndroidApi\SectionController
    prefix: android/sections
    options:
        expose: true

android_country:
    type: rest
    resource: MainBundle\Controller\AndroidApi\CountryController
    prefix: android/countries
    options:
        expose: true

