notification:
    type: rest
    resource: MainBundle\Controller\Api\NotificationController
    prefix: notifications
    options:
        expose: true

country:
    type: rest
    resource: MainBundle\Controller\Api\CountryController
    prefix: country
    options:
        expose: true