imports:
    - { resource: 'services/adapters.yml' }
    - { resource: 'services/creators.yml' }
    - { resource: 'services/helpers.yml' }
    - { resource: 'services/fetchers.yml' }
    - { resource: 'services/readers.yml' }
    - { resource: 'services/managers.yml' }
    - { resource: 'services/voters.yml' }
    - { resource: 'services/services.yml' }
